### ISSUE TITLE
Required files for RNA velocity (mouse version)

### ISSUE THREAD

**Issue by zakiF** [BUStools/getting_started#1]
Hi, 

Not sure if this post is considered an issue or leaning more to a question. The RNA velocity [tutorial](https://www.kallistobus.tools/velocity_tutorial.html) provided links to download materials for human genome, for instance ;

- Human cDNA Transcripts 
- Human introns Transcripts 
- cDNA Transcripts to Capture 
- Introns Transcripts to Capture 
- cDNA/introns Transcripts to Genes map 

I was wondering if the required files for mouse version can be provided as well? In addition I am hoping to use the bustools / RNA velocity workflow from SmartSeq2 sequencing fastq files, is the current workflow compatible for SmartSeq protocol? 

Best
Zaki

**Comment by lambdamoses** [comment]
Sorry for the confusion. We will post a tutorial on how to generate those files soon, later this week or next week. I don't think the kallisto bus pipeline will work for SmartSeq2. The technology must be UMI based (the u in `bus` means UMI). Use `kallisto bus --list` to see  the list of technologies supported.

**Comment by sbooeshaghi** [comment]
The files to reproduce figure 3 in the manuscript (mouse) are located here:

https://github.com/pachterlab/MBGBLHGP_2019/releases/tag/figure_3_files
